name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
       
    - name: build
      run: go build . 
      
    - name: lint
      uses: golangci/golangci-lint-action@v6.5.0
      with:
        version: latest
    
    - name: test
      run: go test -v ./...
